#!/usr/bin/env python3
"""
One command -> a clean, easy-to-share model report (MODEL_REPORT.md):
  - mAP@0.5 + per-class AP table
  - a 50-image ground-truth-vs-prediction montage
  - how much the model has trained
  - an expected-improvement note vs the prior baseline

Run after training + FPGA export, e.g.:
  python scripts/make_report.py \
      --ir runs/unified_pku_yolo_gray640/openvino_fpga/yolov3_fpga_fp32.xml \
      --data datasets/unified_pku_yolo_gray640 \
      --classes runs/unified_pku_yolo_gray640/openvino_fpga/classes.txt \
      --trained "phase 1: 30 epochs frozen + phase 2: 20 epochs unfrozen, H100" \
      --baseline 0.408
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def _run(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True)
    return p.stdout + p.stderr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ir", required=True, help="OpenVINO IR .xml (FPGA raw or decoded)")
    ap.add_argument("--data", required=True)
    ap.add_argument("--split", default="test")
    ap.add_argument("--classes", required=True)
    ap.add_argument("--trained", default="(unspecified)",
                    help="human description of how much training was done")
    ap.add_argument("--baseline", default="0.408",
                    help="prior mAP@0.5 to compare the new number against")
    ap.add_argument("--montage-n", type=int, default=50)
    ap.add_argument("--montage", default="docs/eval_samples.jpg")
    ap.add_argument("--out", default=str(ROOT / "MODEL_REPORT.md"))
    ap.add_argument("--py", default=sys.executable)
    args = ap.parse_args()

    py = args.py
    print("[1/3] evaluating mAP on", args.split, "...")
    ev = _run([py, str(ROOT / "scripts/analyze_openvino.py"), "--ir", args.ir,
               "--data", args.data, "--split", args.split, "--classes", args.classes,
               "--samples", "0"])
    per_class, mAP = [], None
    for line in ev.splitlines():
        m = re.match(r"\s*([A-Za-z_]+)\s+(\d+)\s+(\d+)\s+([\d.]+)\s*$", line)
        if m:
            per_class.append(m.groups())
        mm = re.search(r"mAP@0\.5\s*=\s*([\d.]+)", line)
        if mm:
            mAP = mm.group(1)
    if mAP is None:
        print("  WARNING: could not parse mAP. analyze output:\n", ev[-800:])

    print(f"[2/3] building {args.montage_n}-image montage ...")
    _run([py, str(ROOT / "scripts/make_report_samples.py"), "--ir", args.ir,
          "--data", args.data, "--split", args.split, "--classes", args.classes,
          "--n", str(args.montage_n), "--out", args.montage])

    print("[3/3] writing", args.out)
    img_dir = Path(args.data) / args.split / "images"
    n_images = sum(1 for p in img_dir.iterdir()
                   if p.suffix.lower() in {".png", ".jpg", ".jpeg", ".bmp"})
    n_gt = sum(int(r[1]) for r in per_class)
    classes = Path(args.classes).read_text().split()
    rows = "\n".join(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} |" for r in per_class)
    try:
        delta = float(mAP) - float(args.baseline)
        if abs(delta) < 1e-9:
            delta_txt = "current baseline"
        else:
            delta_txt = f"{'+' if delta >= 0 else ''}{delta:.3f} vs the {args.baseline} baseline"
    except (TypeError, ValueError):
        delta_txt = f"baseline {args.baseline}"

    md = f"""# PCB Defect Detector — Model Report

YOLOv3 (transfer-learned) for 6 PCB defect classes, exported for Intel FPGA AI Suite
(Agilex 7 F-series). Generated by `scripts/make_report.py`.

## Headline

| Metric | Value |
|--------|-------|
| **mAP@0.5 (test)** | **{mAP}** ({delta_txt}) |
| Test images | {n_images} (held-out, never seen in training) |
| Defect instances (test) | {n_gt} |
| Classes | {', '.join(classes)} |
| Training so far | {args.trained} |

## Accuracy by class

| Class | Ground truths | Predictions | AP@0.5 |
|-------|--------------:|------------:|-------:|
{rows}

## How much it has trained

{args.trained}

mAP is reported on the **held-out test split** (boards never seen in training, in any
augmentation), so it's an honest generalization estimate, not a memorized score.

## Expected improvement with more training

The biggest accuracy levers, roughly in order of impact:

1. **Full training to convergence + backbone unfreeze.** A frozen-backbone warm-up only
   adapts the detection heads; unfreezing lets the Darknet features adapt to the
   grayscale-PCB domain (far from COCO). This is usually the single largest gain.
2. **k-means anchors** (implemented; mean box↔anchor IoU 0.63→0.77, applied from the next
   run) mainly help the smallest classes (`spur`, `spurious_copper`) where recall lags.
3. **More data + augmentation** (DeepPCB added to train; online flips/rotation/brightness)
   improve robustness and reduce overfitting.

For HRIPCB-class PCB defect detection, well-trained YOLOv3 models typically reach
**~0.60–0.80 mAP@0.5**. Treat that as a target range, not a guarantee — the realized
number depends on convergence, and `spur`/`spurious_copper` recall is the part to watch.
Compare any new run directly against the **{args.baseline}** baseline since val/test are
unchanged.

## Sample predictions (test set)

Each sample is a pair: **left = ground truth (green)**, **right = model prediction (red,
with class + confidence)**. Balanced across the source datasets; `[Source]` tag on each.

![Sample predictions — left: ground truth (green), right: prediction (red)]({args.montage})

---
*Regenerate anytime: `python scripts/make_report.py --ir <…>.xml --data <dataset> --classes <…> --trained "<note>"`.*
"""
    Path(args.out).write_text(md)
    print("done. mAP@0.5 =", mAP, "->", args.out)


if __name__ == "__main__":
    main()
